language: php

sudo: true
dist: trusty
group: edge

php:
  - hhvm-3.15

#addons:
#  postgresql: "9.3"
#
#services:
#  - memcached # will start memcached

before_install:
  - composer self-update
#  - sh -e build/travis/scripts/apt-get.sh
#  - sh -e build/travis/scripts/apache2-vhost.sh
#  - sh -e build/travis/scripts/apache2-configure.sh

before_script:
  - composer install --ignore-platform-reqs --no-interaction
  - if [[ ${TRAVIS_PHP_VERSION} == "hhvm-3.15" ]]; then cat build/config/hhvm.ini >> /etc/hhvm/php.ini; fi
#  - phpenv rehash

script:
  - phpunit --configuration phpunit.travis.xml
